### ISSUE TITLE
[PE-D][Tester C] Unable to View Contacts After Using Find Command

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-F11-4/tp#152]
After trying to find a person that does not exist this is the window I am provided with:

![image.png](https://raw.githubusercontent.com/chuahjiajie/ped/main/files/4d4bcc08-c898-4462-9d83-59d996d4408b.png)

There is no way for me to view the old contacts list without the knowledge of the list command. 

It would be better if the list command was written as a hint after "0 Persons Listed"

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: chuahjiajie/ped#4

**Comment by donwong2308** [comment]
Can add tip to UG
