### ISSUE TITLE
[PE-D][Tester B] Very Long names get truncated

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-F11-4/tp#161]
Steps taken: Run `add n/a.........b p/98765431`

Expected: Full name to still be displayed

Actual: Name is truncated as the "b" at the end is not displayed

Screenshot:

![image.png](https://raw.githubusercontent.com/appleraincoat/ped/main/files/57709c42-4620-4451-a822-4dda03afc79a.png)

Suggestion:
Consider using line wrapping to allow display of names to occupy multiple lines, no truncation is needed this way.

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: appleraincoat/ped#5

**Comment by PallonCX** [comment]
<img width="759" alt="Screenshot 2024-04-12 at 1 17 11 PM" src="https://github.com/AY2324S2-CS2103T-F11-4/tp/assets/102943362/6aed8e94-184f-468f-9888-5b6f5bb30f0c">

I don't think we have a good reason to restrict people's name length for our app, so the only way is to solve the UI.
