### ISSUE TITLE
[PE-D][Tester A] Typo in UG for quick start

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-F11-4/tp#182]
![image.png](https://raw.githubusercontent.com/CJerrong/ped/main/files/74df4a50-b0ff-4a9a-a23d-9f5f9e6ba9ce.png)
There is a slightly typo in the UG for the Quick Start section, should perhaps be `Paste`

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: CJerrong/ped#11

**Comment by PallonCX** [comment]
UG Fix
