### ISSUE TITLE
[PE-D][Tester B] Help is not very useful

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-F11-4/tp#191]
`help` is not very useful as it only leads to another link to the UG.

Consider changing the Help Window to display a short summary of how to use all the commands, so that the user can get comprehensive help without leaving the app

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: appleraincoat/ped#11

**Comment by PallonCX** [comment]
Just suggestion.
