### ISSUE TITLE
[PE-D][Tester B] Long black bars in empty parts of the window

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-F11-4/tp#194]
The empty space is filled by long black bars, presumably from the UI of the previous version of this app (AddressBook).

![image.png](https://raw.githubusercontent.com/appleraincoat/ped/main/files/36fc4db8-d04b-46f8-b6e6-b0876167e184.png)

Consider changing its colour to something that is consistent with the theme of your current app :)

-------------
Labels: `type.FeatureFlaw` `severity.VeryLow`
original: appleraincoat/ped#14

**Comment by PallonCX** [comment]
Cosmetic issue.
