### ISSUE TITLE
[PE-D][Tester D] Behaviour of Commands dealing with Email Fields does not match expected behaviour.

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-F11-4/tp#205]
Under the Contact Fields section of the User Guide, valid contact emails "Must contain @ and .com", as shown in the screenshot below:

![image.png](https://raw.githubusercontent.com/jamessinmaojun/ped/main/files/20bef783-ea2c-44f4-83a0-ee725cddd0c6.png)

However, when I try to define a contact email with a different domain extension (using the add command and `.net` as the domain extension for example as shown below), the application fails to parse the email as invalid.

![image.png](https://raw.githubusercontent.com/jamessinmaojun/ped/main/files/637c0d35-a08a-4beb-bbc9-e301317511ad.png)

The problem here is that email parser did not check for a `.com` extension, which was specified as a must-have in the Contact Fields Table. Therefore the application is inconsistent with the User Guide.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: jamessinmaojun/ped#17

**Comment by donwong2308** [comment]
Edit the regex for email
