### ISSUE TITLE
[PE-D][Tester C] Clear Command is Risky

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-F11-4/tp#211]
Current implementation of clear command does not prompt the user to confirm, nor is there is particularly strong use case for this command.

![image.png](https://raw.githubusercontent.com/chuahjiajie/ped/main/files/b64ec808-d9bb-4145-bd9f-900ccbda1510.png)

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: chuahjiajie/ped#17

**Comment by larainezo** [comment]
Proposed fix:
- Add a warning in UG
