### ISSUE TITLE
[PE-D][Tester C] Edit Command for Room Does not Specify What the Correct Format is Precisely Enough

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-F11-4/tp#214]
![image.png](https://raw.githubusercontent.com/chuahjiajie/ped/main/files/86ae5ce2-d688-4af7-a4eb-728d23bd4b08.png)

It is not obvious enough why this is failing.

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: chuahjiajie/ped#20

**Comment by larainezo** [comment]
Proposed fix:
- Specify the proper room number format more precisely in UG
- Specify the proper room number format more precisely in code
